export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const LOAN_APPROVAL_REQUEST = "LOAN_APPROVAL_REQUEST";
export const LOAN_APPROVAL_SUCCESS = "LOAN_APPROVAL_SUCCESS";
export const LOAN_APPROVAL_FAILURE = "LOAN_APPROVAL_FAILURE";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
